@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 5
skinparam maxmessagesize 180
skinparam sequenceParticipant bold
title GET Practitioner
actor "Integrating application user" as User #CornflowerBlue
participant "Integrating application" as A #CornflowerBlue
participant "<FHIR API> HPI" as B #CornflowerBlue
participant "HPI MDM" as C #CornflowerBlue
|||
User -> A: Look up Practitioner using hpi-person-id
activate A
|||
A -> B: GET (…)/Practitioner/[hpi-person-id]
activate B
|||
B -> B: Validate[]
|||
B -> C: Request
activate C
|||

C -[dashed]-> B:  
deactivate C
|||
B -[dashed]-> A:Return Practitioner record
deactivate B
|||
A -> User: Display Practitioner details
deactivate A
|||
@enduml
