@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 5
skinparam maxmessagesize 180
skinparam sequenceParticipant bold
title Get Facility (Location) sequence diagram
actor "Integrating application user" as User #CornflowerBlue
participant "Integrating application" as A #CornflowerBlue
participant "<FHIR API> HPI" as B #CornflowerBlue
participant "HPI MDM" as C #CornflowerBlue
|||
User -> A: Look up facility with hpi-facility-id
activate A
|||
A -> B: GET<Endpoint>/Location/[hpi-facility-id]
activate B
|||
B -> B: Validate[]
|||
B -> C: Request
activate C
|||

C -[dashed]-> B:  
deactivate C
|||
B -[dashed]-> A:Return Location record
deactivate B
|||
A -> User: Display Facility (Location) details
deactivate A
|||
@enduml
