@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 5
skinparam maxmessagesize 180
skinparam sequenceParticipant bold
title GET location (facility) 
actor "Integrating application user" as User #CornflowerBlue
participant "Integrating application" as A #CornflowerBlue
participant "<FHIR API> NHI" as B #CornflowerBlue
participant "HPI MDM" as C #CornflowerBlue
|||
User -> A: Look up location with facId
activate A
|||
A -> B: GET (…)/location/[facId]
activate B
|||
B -> B: Validate[]
|||
B -> C: Request
activate C
|||

C -[dashed]-> B:  
deactivate C
|||
B -[dashed]-> A:
deactivate B
|||
A -> User: Return location record
deactivate A
|||
@enduml
