@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 5
skinparam maxmessagesize 180
skinparam sequenceParticipant bold
title GET Practitioner role
actor "Integrating application user" as User #CornflowerBlue
participant "Integrating application" as A #CornflowerBlue
participant "<FHIR API> HPI" as B #CornflowerBlue
participant "HPI Practitioner Role database" as C #CornflowerBlue
|||
User -> A: Look up PractitionerRole with hpi-practitionerrole-id
activate A
|||
A -> B: GET<Endpoint>/PractitionerRole/[hpi-practitionerrole-id]
activate B
|||
B -> B: Validate[]
|||
B -> C: Request
activate C
|||
C -[dashed]-> B:  
deactivate C
|||
B -[dashed]-> A:Return PractitionerRole record
deactivate B
|||
A -> User: Return PractitionerRole details
deactivate A
|||
@endumlp
