@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 5
skinparam maxmessagesize 180
skinparam sequenceParticipant bold
title Query Facility using NZHIS (Legacy) identifier sequence diagram 
actor "Integrating application user" as User #CornflowerBlue
participant "Integrating application" as A #CornflowerBlue
participant "<FHIR API> HPI" as B #CornflowerBlue
participant "HPI MDM" as C #CornflowerBlue
|||
User -> A: User enters NZHIS (Legacy) identifier and identifier system
activate A
|||
A -> B: GET<Endpoint>/Location?identifier=[system]|[identifier]
activate B
|||
B -> B: Validate[]
|||
B -> C: Get[Location]
activate C
|||
C -[dashed]-> B:  
deactivate C
|||
B -[dashed]-> A:Return Bundle containing the Facility record
deactivate B
|||
A -> User: Display Facility details to user
deactivate A
|||
@enduml
