@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 5
skinparam maxmessagesize 180
skinparam sequenceParticipant bold
title Search Organisation by type sequence diagram
actor "Integrating application user" as User #CornflowerBlue
participant "Integrating application" as A #CornflowerBlue
participant "<FHIR API> HPI" as B #CornflowerBlue
participant "HPI MDM" as C #CornflowerBlue
|||
User -> A: Enters HPI organisation type e.g. PHO
activate A
|||
A -> B: GET<Endpoint>/Organization?type=[]
activate B
|||
B -> B: Validate[]
|||
B -> C: Search[type]
activate C
|||
C -[dashed]-> B:  
deactivate C
|||
B -[dashed]-> A:Return(bundle)
deactivate B
|||
A -> User: Return list of matching organisations
deactivate A
|||
@enduml
