@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 5
skinparam maxmessagesize 180
skinparam sequenceParticipant bold
title Search Organization by name
actor "Integrating application user" as User #CornflowerBlue
participant "Integrating application" as A #CornflowerBlue
participant "<FHIR API> HPI" as B #CornflowerBlue
participant "HPI MDM" as C #CornflowerBlue
|||
User -> A: Search organization by name
activate A
|||
A -> B: GET\{{Endpoint}}/Organization?name=[]
activate B
|||
B -> B: Validate[]
|||
B -> C: Search[name]
activate C
|||
C -[dashed]-> B:  
deactivate C
|||
B -[dashed]-> A:Return(bundle)
deactivate B
|||
A -> User: Return list of matching organizations
deactivate A
|||
@enduml
