
# ╭────────────────────────────ImplementationGuide-hl7.org.nz.hpi.json─────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  http://build.fhir.org/ig/HL7/fhir-shorthand/branches/beta/sushi.html#ig-development           │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.org.nz.fhir.ig.hpi
canonical: http://hl7.org.nz/fhir/ig/hpi
#canonical: http://build.fhir.org/ig/HL7NZ/nzbase/branches/master
version: 1.0.0
name: NewZealandHPIIG
title: New Zealand HPI Implementation Guide
status: active
publisher:
  name: Ministry of Health
  email: mailto:integration@health.govt.nz
description: The HPI facade
license: CC0-1.0
fhirVersion: 4.0.1

dependencies:

  hl7.org.nz.fhir.ig.hip-core:
     uri: 'https://nzhts.digital.health.nz/ig/hip-common-terminology'
     version: 1.0.0
     
  # there is a dependency on NZBase to get the extensions defined in there  
  fhir.org.nz.ig.base:
     uri: 'http://fhir.org.nz/ig/base'
     version: 1.0.0
    

     
parameters:
  show-inherited-invariants: false

copyrightYear: 2020+
releaseLabel: Release

# ╭─────────────────────────────────────────────ig.ini─────────────────────────────────────────────╮
# │  To use a provided ig-data/ig.ini file, delete the "template" property below.                  │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
# template: fhir.base.template#current


# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To control the menu.xml using this config, uncomment and set the "menu" property.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  IG Home: index.html
  Business View: businessView.html
  Use cases:
    Composite use cases: Compositeusecases.html
    Get Practitioner: getPractitioner.html
    Search Practitioner: searchPractitioner.html
    Add Practitioner: addPractitioner.html
    Get Practitioner Role: getPracRole.html
    Search Practitioner Role: searchPracRole.html
    Add Practitioner Role: addPracRole.html
    Update Practitioner Role: updatePracRole.html
    Get Facility (Location): getLocation.html
    Search Facility (Location): searchLocation.html
    Get Organization: getOrganization.html
    Search Organization: searchOrganization.html
  Important information:
    Onboarding and Compliance testing: OnboardingAndComplianceTesting.html
    General Notes: general.html
    FAQ: faq.html
  API: capabilityStatement.html
  Profiles: profiles.html
  Extensions: extensions.html
  Terminology: terminology.html
  Table of Contents: toc.html
  Artifact Index: artifacts.html
  Support:
    "FHIR Spec ": "{{site.data.fhir.path}}index.html"
    "Download IG" : full-ig.zip
    Artifacts (Json): definitions.json.zip
    Artifacts (Xml): definitions.xml.zip
    "OpenApi 3 spec": HpiFhirOpenApi.zip
