
# ╭────────────────────────────ImplementationGuide-hl7.org.nz.hpi.json─────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  http://build.fhir.org/ig/HL7/fhir-shorthand/branches/beta/sushi.html#ig-development           │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: tewhatuora.hpi
canonical: https://fhir-ig.digital.health.nz
#canonical: http://build.fhir.org/ig/HL7NZ/nzbase/branches/master
version: 1.5.0
name: NewZealandHPIIG
title: New Zealand HPI Implementation Guide
status: active
publisher:
  name: Te Whatu Ora
  email: mailto:integration@health.govt.nz
description: The HPI facade
license: CC0-1.0
date: 2024-09-06
fhirVersion: 4.0.1
  
dependencies:
  tewhatuora.digitaltooling: 
    version: 0.0.11
  tewhatuora.hip-core:
     uri: https://fhir-ig.digital.health.nz/HIP-FHIR-Common
     version: 1.9.1
     
  # there is a dependency on NZBase to get the extensions defined in there  
  fhir.org.nz.ig.base:
    #uri: 'http://build.fhir.org/ig/HL7NZ/nzbase/branches/master'
    uri: 'https://fhir.org.nz/ig/base/ns'
    #version: dev
    version: 3.0.0
    

     
parameters:
  show-inherited-invariants: false
  bundle-references-resolve: false
  default-contact: true              # publish contact info for all resources (using canonical meta contact where specified)
  apply-version: false               # stop publisher from overwriting artefact-specific versions
  default-version: true              # versions of canonicals that specify their own version no longer overwritten by the IG publisher
  suppressed-ids: $examples          # stop IG publisher generating ids for all example resource instances
  display-warnings: true 
  usage-stats-opt-out: 'true'
  special-url:
    # standards canonical urls
    - https://hpi-ig.hip.digital.health.nz/OperationDefinition/practitioner-update-core
    - http://hl7.org.nz/fhir/StructureDefinition/HPIPractitioner
    - http://hl7.org.nz/fhir/StructureDefinition/HPIPractitionerRole
    - http://hl7.org.nz/fhir/StructureDefinition/HPILocation
    - http://hl7.org.nz/fhir/StructureDefinition/HPIOrganization
    - http://hl7.org.nz/fhir/StructureDefinition/esam-id

copyrightYear: 2020+
releaseLabel: Release

# ╭─────────────────────────────────────────────ig.ini─────────────────────────────────────────────╮
# │  To use a provided ig-data/ig.ini file, delete the "template" property below.                  │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
# template: fhir.base.template#current


# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To control the menu.xml using this config, uncomment and set the "menu" property.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  IG Home: index.html
  Business View: businessView.html
  Use cases:
    Guidance: Guidance.html
    Get Facility (Location): getFacility.html
    Search Facility (Location): searchFacility.html
    Get Organisation: getOrganisation.html
    Search Organisation: searchOrganisation.html
    Get Practitioner: getPractitioner.html
    Search Practitioner: searchPractitioner.html
    Create Practitioner: createPractitioner.html
    Update Practitioner: updatePractitioner.html
    Get PractitionerRole: getPracRole.html
    Search PractitionerRole: searchPracRole.html
    Create PractitionerRole: createPracRole.html
    Update PractitionerRole: updatePracRole.html
  Important information:
    Onboarding: Onboarding.html
    General Notes: general.html
    FAQ: faq.html
    Glossary: glossary.html
  Compliance testing:
    Compliance testing important information: ComplianceTestingImportantInformation.html
    Organisation Compliance testing: OrganisationComplianceTesting.html
    Facility Compliance testing: FacilityComplianceTesting.html
    Practitioner Compliance testing: PractitionerComplianceTesting.html
    PractitionerRole Compliance testing: PractitionerRoleComplianceTesting.html
  #API: API.html
  Profiles: profiles.html
  Extensions: extensions.html
  Terminology: terminology.html
  Table of Contents: toc.html
  Artifact Index: artifacts.html
  Support:
    "FHIR Spec ": "{{site.data.fhir.path}}index.html"
    "Download IG" : full-ig.zip
    Artifacts (Json): definitions.json.zip
    Artifacts (Xml): definitions.xml.zip
    #"OpenApi 3 spec": HipFhirHpiOpenApi.zip
    
