
# ╭────────────────────────────ImplementationGuide-hl7.org.nz.hpi.json─────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  http://build.fhir.org/ig/HL7/fhir-shorthand/branches/beta/sushi.html#ig-development           │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.org.nz.fhir.ig.hpi
canonical: http://hl7.org.nz/fhir/ig/hpi
version: 0.9.0
name: NewZealandHPIIG
title: New Zealand HPI Implementation Guide
status: active
publisher:
  name: Ministry of Health
  email: mailto:integration@health.govt.nz
description: The HPI facade
license: CC0-1.0
fhirVersion: 4.0.1

# there is a dependency on NZBase to get the extensions defined in there
dependencies:
  hl7.org.nz.fhir.ig.base: current

parameters:
  show-inherited-invariants: false
copyrightYear: 2020+
releaseLabel: CI Build

# ╭─────────────────────────────────────────────ig.ini─────────────────────────────────────────────╮
# │  To use a provided ig-data/ig.ini file, delete the "template" property below.                  │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
# template: fhir.base.template#current


# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To control the menu.xml using this config, uncomment and set the "menu" property.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  IG Home: index.html
  Business View: businessView.html
  Use cases: usecases.html
  General Notes: general.html
  Logical Models: logical.html
  API: capabilityStatement.html
  FAQ: faq.html
  Profiles: profiles.html
  Extensions: extensions.html
  Terminology: terminology.html
  Artifact Index: artifacts.html
  Support:
    "FHIR Spec ": "{{site.data.fhir.path}}index.html"
    "Full IG" : full-ig.zip
